Repository ChatFlowProject/chatter, pull requests merged in 2025-05, with the labels that each got.

#51 [feat/api/server-channel] FLOW-28: 로그인 확인 완료
  src/service/feature/auth/hook/auth/useLogin.ts
Labels: bug

#52 [Feat/component/inbox/FLOW-20] 받은 편지함 컴포넌트 구현
  public/assets/img/inbox.svg
  public/logo.png
  src/app/Router.tsx
  src/service/feature/team/api/teamsServiceAPI.ts
  src/view/components/layout/sidebar/components/top/ChatMessage.tsx
  src/view/components/layout/sidebar/components/top/ForYou.tsx
  src/view/components/layout/sidebar/components/top/Inbox.tsx
  src/view/components/layout/sidebar/components/top/Mention.tsx
  src/view/components/layout/sidebar/components/top/Message.tsx
  src/view/components/layout/sidebar/top/TopSidebar.tsx
  src/view/layout/LayoutWithSidebar.tsx
  src/view/layout/profile/UserProfileBar.tsx
  src/view/layout/sidebar/components/channel/DirectMessages.tsx
Labels: bug, component

#53 [Feat/component/invite friend/FLOW-30] 팀에 친구 초대 기능 구현
  src/app/Router.tsx
  src/service/feature/auth/api/authAPI.ts
  src/service/feature/auth/api/profileAPI.ts
  src/service/feature/auth/hook/auth/useLogin.ts
  src/service/feature/channel/api/channelAPI.ts
  src/service/feature/channel/hook/query/useChannelQuery.ts
  src/service/feature/channel/types/channel.ts
  src/service/feature/chat/api/chatAPI.ts
  src/service/feature/common/axios/axiosInstance.ts
  src/service/feature/friend/api/friendApi.ts
  src/service/feature/friend/hook/useFriendQuery.ts
  src/service/feature/image/imageApi.ts
  src/service/feature/member/api/memberAPI.ts
  src/service/feature/team/api/teamsMemberAPI.ts
  src/service/feature/team/api/teamsServiceAPI.ts
  src/view/components/common/Modal.tsx
  src/view/layout/sidebar/components/channel/InviteFriendModal.tsx
  src/view/layout/sidebar/components/channel/Item.tsx
  src/view/layout/sidebar/components/channel/ServerChannelList.tsx
  src/view/pages/Friends/components/UserCard.tsx
Labels: bug, action, feature
