Repository ChatFlowProject/chatter, pull requests merged in 2025-04, with the labels that each got.

#39 [feat/component/flow-6] 브랜치 병합
  index.html
  src/assets/cancel-btn.svg
  src/assets/profile.svg
  src/assets/right-arrow.svg
  src/assets/warning.svg
  src/components/shared/Alarm.tsx
  src/components/shared/ContextMenu.tsx
  src/components/shared/Modal.tsx
  tailwind.config.js
Labels: merge

#45 [Feat/component/server channel/flow-27] ServerChannelSidebar 구성 및 채널 DnD 기능 추가
  .gitignore
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/app/Router.tsx
  src/service/feature/channel/hook/useChannelList.ts
  src/service/feature/chat/hook/useChannelList.ts
  src/service/feature/chat/index.ts
  src/view/components/layout/Header.tsx
  src/view/components/layout/LayoutWithSidebar.tsx
  src/view/components/layout/UserProfileBar.tsx
  src/view/components/layout/sidebar/ChannelSidebar.tsx
  src/view/components/layout/sidebar/channel/DirectChannelSidebar.tsx
  src/view/components/layout/sidebar/channel/ServerChannelSidebar.tsx
  src/view/components/layout/sidebar/component/channel/ChannelNavigation.tsx
  src/view/components/layout/sidebar/component/channel/NavigationCard.tsx
  src/view/components/layout/sidebar/component/right/DirectBar.tsx
  src/view/components/layout/sidebar/components/channel/ChannelCategory.tsx
  src/view/components/layout/sidebar/components/channel/ChannelItem.tsx
  src/view/components/layout/sidebar/components/channel/ChannelNavigation.tsx
  src/view/components/layout/sidebar/components/channel/DirectMessages.tsx
  src/view/components/layout/sidebar/components/channel/NavigationCard.tsx
  src/view/components/layout/sidebar/components/channel/ServerChannelList.tsx
  src/view/components/layout/sidebar/components/channel/SidebarLayout.tsx
  src/view/components/layout/sidebar/components/profile/Interactions.tsx
  src/view/components/layout/sidebar/components/profile/ProfileInfo.tsx
  src/view/components/layout/sidebar/components/profile/UserInfo.tsx
  src/view/components/layout/sidebar/components/profile/UserProfile.tsx
  src/view/pages/chat/ChatPage.tsx
  src/view/pages/legacy/HomePage.tsx
  tsconfig.app.json
Labels: component

#48 [Feat/api/server channel/flow 28] 서버 생성/리스트 조회 기능 API 연동
  Dockerfile
  docker-deploy.sh
  src/service/feature/auth/api/authAPI.ts
  src/service/feature/auth/hook/useLogin.ts
  src/service/feature/auth/hook/useProfileQuery.ts
  src/service/feature/auth/hook/useRegister.ts
  src/service/feature/auth/types/auth.ts
  src/service/feature/channel/api/channelAPI.ts
  src/service/feature/channel/hook/mutation/useChannelMutation.ts
  src/service/feature/channel/hook/query/useChannelQuery.ts
  src/service/feature/channel/hook/useChannelList.ts
  src/service/feature/channel/types/channel.ts
  src/service/feature/chat/api/chatAPI.ts
  src/service/feature/chat/index.ts
  src/service/feature/common/axios/axiosInstance.ts
  src/service/feature/common/axios/chatInstance.ts
  src/service/feature/friend/api/friendApi.ts
  src/service/feature/member/api/memberAPI.ts
  src/service/feature/member/hook/useMemberQuery.ts
  src/service/feature/member/types/memberAPI.ts
  src/service/feature/team/api/teamsMemberAPI.ts
  src/service/feature/team/api/teamsServiceAPI.ts
  src/service/feature/team/hook/mutation/useCreateTeamMutation.ts
  src/service/feature/team/hook/mutation/useTeamMemberMutation.ts
  src/service/feature/team/hook/mutation/useTeamServiceMutation.ts
  src/service/feature/team/hook/query/useTeamServiceQuery.ts
  src/view/components/common/ContextMenu.tsx
  src/view/components/common/Modal.tsx
  src/view/components/layout/LayoutWithSidebar.tsx
  src/view/components/layout/sidebar/components/channel/ChannelCategory.tsx
  src/view/components/layout/sidebar/components/channel/ChannelItem.tsx
  src/view/components/layout/sidebar/components/channel/ChannelNavigation.tsx
  src/view/components/layout/sidebar/components/channel/NavigationCard.tsx
  src/view/components/layout/sidebar/components/channel/ServerChannelList.tsx
  src/view/pages/Friends/components/Topbar.tsx
  src/view/pages/Friends/components/UserCard.tsx
  src/view/pages/chat/components/AddServerModal.tsx
  tsconfig.app.json
Labels: API

#49 [feat/component/create-server/FLOW-22] 서버 생성 에러 수정
  src/service/feature/image/imageApi.ts
  src/service/feature/team/api/teamApi.ts
  src/view/pages/chat/components/AddServerModal.tsx
Labels: bug
