Repository ChatFlowProject/chatter, pull requests merged in 2025-02, with the labels that each got.

#22 chore(#FLOW-4): vite에서 webpack으로 번들러 마이그레이션
  .babelrc
  index.html
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  webpack.config.js
  yarn.lock
Labels: setting

#23 chore(#FLOW-1) setting tailwind config
  webpack.config.cjs
Labels: setting

#24 [Feat/setting/FLOW-2] 브랜치 병합(setting -> develop)
  .babelrc
  index.html
  package-lock.json
  package.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  webpack.config.js
  yarn.lock
Labels: merge

#30 [FLOW-7] feat: chat input 컴포넌트 추가
  src/components/.gitkeep
  src/components/chat/ChatInput.tsx
  src/components/chat/Message.tsx
  src/components/chat/Reply.tsx
  src/components/shared/Button.tsx
  src/components/shared/Checkbox.tsx
  src/components/shared/DropDown.tsx
  src/components/user/LoginLabel.tsx
  src/components/user/LoginTextInput.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/SignupPage/DatePicker.tsx
  src/pages/SignupPage/SignupForm.tsx
  tailwind.config.js
Labels: component

#31 [Feat/component/FLOW-6] develop 브랜치로 병합
  src/api/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/components/chat/ChatInput.tsx
  src/components/chat/Message.tsx
  src/components/chat/Reply.tsx
  src/components/shared/Button.tsx
  src/components/shared/Checkbox.tsx
  src/components/shared/DropDown.tsx
  src/components/user/LoginLabel.tsx
  src/components/user/LoginTextInput.tsx
  src/pages/Login/components/LoginForm.tsx
  src/pages/SignupPage/DatePicker.tsx
  src/pages/SignupPage/SignupForm.tsx
  tailwind.config.js
Labels: merge
